name: Erro
about: Relatar comportamento incorreto
title: "fix: "
labels: [bug]
body:
  - type: textarea
    attributes: {label: Descrição}
    validations: {required: true}
  - type: textarea
    attributes: {label: Passos para reproduzir}
    validations: {required: true}
  - type: input
    attributes: {label: Versão}
