services:
  auditor-fiscal-app-init:
    image: auditor-fiscal/api:pr

  auditor-fiscal-api:
    image: auditor-fiscal/api:pr
    ports:
      - "127.0.0.1:18080:8080"

  auditor-fiscal-web:
    image: auditor-fiscal/web:pr

  auditor-fiscal-engine:
    image: auditor-fiscal/fiscal-engine:pr
    ports:
      - "127.0.0.1:18082:8000"
