<?php
use App\Http\Controllers\{AnalysisController,ApplicationLogController,AuthController,CatalogController,CompanyController,DashboardController,HealthController,ReportController,TenantController,UserController}; use Illuminate\Support\Facades\Route;
Route::prefix('v1')->group(function(){
 Route::get('health/live',[HealthController::class,'live']);Route::get('health/ready',[HealthController::class,'ready']);Route::post('auth/login',[AuthController::class,'login'])->middleware('throttle:10,1');
 Route::middleware('auth:sanctum')->group(function(){
  Route::get('auth/me',[AuthController::class,'me']);Route::post('auth/logout',[AuthController::class,'logout']);Route::get('dashboard',DashboardController::class);
  Route::get('tenants',[TenantController::class,'index'])->middleware('permission:tenants.view');Route::post('tenants/lookup-cnpj',[TenantController::class,'lookup'])->middleware(['permission:tenants.manage','throttle:10,1']);Route::post('tenants',[TenantController::class,'store'])->middleware('permission:tenants.manage');Route::patch('tenants/{tenant}',[TenantController::class,'update'])->middleware('permission:tenants.manage');Route::delete('tenants/{tenant}',[TenantController::class,'destroy'])->middleware('permission:tenants.manage');
  Route::get('companies',[CompanyController::class,'index']);Route::post('companies',[CompanyController::class,'store'])->middleware('permission:companies.manage');Route::patch('companies/{company}',[CompanyController::class,'update'])->middleware('permission:companies.manage');Route::delete('companies/{company}',[CompanyController::class,'destroy'])->middleware('permission:companies.manage');
  Route::get('users/roles',[UserController::class,'roles'])->middleware('permission:users.manage');Route::apiResource('users',UserController::class)->only(['index','store','update'])->middleware('permission:users.manage');
  Route::prefix('catalogs')->group(function(){Route::get('/',[CatalogController::class,'versions']);Route::post('import',[CatalogController::class,'import'])->middleware('permission:catalogs.manage');Route::get('{version}',[CatalogController::class,'show']);Route::get('{version}/entries',[CatalogController::class,'entries']);Route::get('{version}/issues',[CatalogController::class,'issues']);Route::post('{version}/revision',[CatalogController::class,'createRevision'])->middleware('permission:catalogs.manage');Route::post('{version}/entries',[CatalogController::class,'storeEntry'])->middleware('permission:catalogs.manage');Route::patch('{version}/entries/{entry}',[CatalogController::class,'updateEntry'])->middleware('permission:catalogs.manage');Route::delete('{version}/entries/{entry}',[CatalogController::class,'deleteEntry'])->middleware('permission:catalogs.manage');Route::post('{version}/publish',[CatalogController::class,'publish'])->middleware('permission:catalogs.publish');Route::get('{version}/compare/{other}',[CatalogController::class,'compare']);});
  Route::prefix('analyses')->group(function(){Route::get('/',[AnalysisController::class,'index']);Route::post('/',[AnalysisController::class,'store'])->middleware('permission:analyses.create');Route::get('{batch}',[AnalysisController::class,'show']);Route::get('{batch}/analytics',[AnalysisController::class,'analytics']);Route::get('{batch}/logs/export',[AnalysisController::class,'exportLogs']);Route::get('{batch}/logs/{log}/download',[AnalysisController::class,'log']);Route::get('{batch}/logs',[AnalysisController::class,'logs']);Route::get('{batch}/documents',[AnalysisController::class,'documents']);Route::get('{batch}/documents/{document}/xml',[AnalysisController::class,'xml']);Route::get('{batch}/documents/{document}/danfe',[AnalysisController::class,'danfe']);Route::get('{batch}/documents/{document}',[AnalysisController::class,'document']);Route::get('{batch}/findings',[AnalysisController::class,'findings']);Route::patch('{batch}/findings/{finding}',[AnalysisController::class,'resolve'])->middleware('permission:analyses.resolve');Route::post('{batch}/reprocess',[AnalysisController::class,'reprocess'])->middleware(['permission:analyses.create','throttle:5,1']);});
  Route::get('application-logs/export',[ApplicationLogController::class,'export'])->middleware('permission:logs.view');Route::get('application-logs/{log}/download',[ApplicationLogController::class,'download'])->middleware('permission:logs.view');Route::get('application-logs',[ApplicationLogController::class,'index'])->middleware('permission:logs.view');
  Route::get('reports/{report}/download',[ReportController::class,'download'])->middleware('permission:reports.download');
 });
});
