<?php
namespace App\Jobs;
use App\Models\{AnalysisBatch,FiscalDocument,FiscalItem,Finding,ReportArtifact}; use Illuminate\Bus\Queueable; use Illuminate\Contracts\Queue\ShouldQueue; use Illuminate\Foundation\Bus\Dispatchable; use Illuminate\Queue\InteractsWithQueue; use Illuminate\Queue\SerializesModels; use Illuminate\Support\Facades\{DB,Http}; use Illuminate\Support\Str; use Throwable;
class ProcessAnalysisBatch implements ShouldQueue {use Dispatchable,InteractsWithQueue,Queueable,SerializesModels;public int $timeout=7200;public int $tries=3;public function __construct(public string $batchId){}
 public function handle():void{$batch=AnalysisBatch::with('company','catalogVersion','sourceFiles')->findOrFail($this->batchId);$batch->update(['status'=>'processing','started_at'=>now(),'progress'=>0.01]);try{$payload=['batch_id'=>$batch->id,'company'=>$batch->company->only(['id','legal_name','trade_name','tax_id','state_registration','timezone']),'catalog_version_id'=>$batch->catalog_version_id,'catalog_version'=>$batch->catalogVersion->version,'catalog_sha256'=>$batch->catalogVersion->source_sha256,'period_start'=>optional($batch->period_start)->format('Y-m-d'),'period_end'=>optional($batch->period_end)->format('Y-m-d'),'source_files'=>$batch->sourceFiles->map->only(['id','original_name','sha256','storage_path'])->values()->all()];$res=Http::timeout(7200)->retry(2,1000)->withToken(config('services.fiscal_engine.token'))->post(config('services.fiscal_engine.url').'/v1/audits/run',$payload);$res->throw();$data=$res->json();DB::transaction(function()use($batch,$data){$docMap=[];$itemMap=[];foreach($data['documents'] as $d){$items=$d['items']??[];unset($d['items']);$ref=$d['document_ref'];unset($d['document_ref']);$d['id']=(string)Str::uuid();$d['analysis_batch_id']=$batch->id;$d['normalized']=json_encode($d['normalized']??[],JSON_UNESCAPED_UNICODE);$document=FiscalDocument::create($d);$docMap[$ref]=$document->id;foreach($items as $i){$itemNo=$i['item_number'];$i['id']=(string)Str::uuid();$i['fiscal_document_id']=$document->id;$i['tax_components']=json_encode($i['tax_components']??[],JSON_UNESCAPED_UNICODE);$i['catalog_match']=json_encode($i['catalog_match']??[],JSON_UNESCAPED_UNICODE);$item=FiscalItem::create($i);$itemMap[$ref.':'.$itemNo]=$item->id;}}
 foreach($data['findings'] as $f){$ref=$f['document_ref']??null;$itemNo=$f['item_number']??null;unset($f['document_ref'],$f['item_number']);$f['id']=(string)Str::uuid();$f['analysis_batch_id']=$batch->id;$f['fiscal_document_id']=$ref?($docMap[$ref]??null):null;$f['fiscal_item_id']=$ref&&$itemNo?($itemMap[$ref.':'.$itemNo]??null):null;$f['evidence']=json_encode($f['evidence']??[],JSON_UNESCAPED_UNICODE);Finding::create($f);}
 foreach($data['reports']??[] as $r)ReportArtifact::create(['analysis_batch_id'=>$batch->id,'type'=>$r['type'],'template_version'=>$r['template_version'],'storage_path'=>$r['storage_path'],'sha256'=>$r['sha256']??null,'size'=>$r['size']??null,'metadata'=>$r['metadata']??[]]);
 $batch->update(['status'=>'completed','processed_files'=>$batch->total_files,'document_count'=>count($data['documents']),'item_count'=>collect($data['documents'])->sum(fn($d)=>count($d['items']??[])),'finding_count'=>count($data['findings']),'progress'=>1,'summary'=>$data['summary']??[],'finished_at'=>now()]);},3);}catch(Throwable $e){$batch->update(['status'=>'failed','error'=>['message'=>$e->getMessage(),'class'=>$e::class],'finished_at'=>now()]);throw $e;}}
 public function failed(?Throwable $e):void{AnalysisBatch::whereKey($this->batchId)->update(['status'=>'failed','error'=>['message'=>$e?->getMessage()],'finished_at'=>now()]);}}
