<?php
namespace App\Http\Controllers;
use App\Jobs\ImportCatalogSpreadsheet; use App\Models\{CatalogImportIssue,CclassCatalogEntry,FiscalCatalogVersion,NcmClassTribEntry}; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB; use Illuminate\Support\Facades\Storage; use Illuminate\Support\Str;
class CatalogController extends Controller {
 public function versions(){return FiscalCatalogVersion::withCount(['ncmEntries','issues'])->latest()->paginate(30);}
 public function show(FiscalCatalogVersion $version){return $version->loadCount(['ncmEntries','cstEntries','cclassEntries','issues']);}
 public function entries(Request $r,FiscalCatalogVersion $version){$q=$version->ncmEntries();foreach(['ncm','expected_cst','expected_cclass_trib','status','ex_code'] as $f)if($r->filled($f))$q->where($f,$r->input($f));if($r->filled('search'))$q->where(fn($x)=>$x->where('description','ilike','%'.$r->search.'%')->orWhere('ncm','like','%'.preg_replace('/\D/','',$r->search).'%'));return $q->orderBy('ncm')->orderBy('ex_code')->paginate(min((int)$r->input('per_page',100),500));}
 public function issues(Request $r,FiscalCatalogVersion $version){$q=$version->issues();if($r->filled('severity'))$q->where('severity',$r->severity);if($r->filled('code'))$q->where('code',$r->code);return $q->latest('id')->paginate(100);}
 public function createRevision(Request $r,FiscalCatalogVersion $version){$r->validate(['version'=>'required|string|max:80|unique:fiscal_catalog_versions,version','name'=>'nullable|string|max:255','valid_from'=>'nullable|date']);return DB::transaction(function()use($r,$version){$new=FiscalCatalogVersion::create(['name'=>$r->name?:$version->name,'version'=>$r->version,'status'=>'draft','valid_from'=>$r->valid_from?:$version->valid_from,'manifest'=>['cloned_from'=>$version->id],'created_by'=>$r->user()->id]);DB::statement('INSERT INTO cst_catalog_entries (catalog_version_id,cst,description,applicable_nfe,indicators,source_sheet,source_row,created_at,updated_at) SELECT ?,cst,description,applicable_nfe,indicators,source_sheet,source_row,now(),now() FROM cst_catalog_entries WHERE catalog_version_id=?',[$new->id,$version->id]);DB::statement('INSERT INTO cclass_catalog_entries (catalog_version_id,cclass_trib,cst,name,description,legal_basis,law_text,rate_type,ibs_reduction_percent,cbs_reduction_percent,valid_from,valid_to,updated_at_source,applicable_nfe,source_url,indicators,format_warning,source_sheet,source_row,created_at,updated_at) SELECT ?,cclass_trib,cst,name,description,legal_basis,law_text,rate_type,ibs_reduction_percent,cbs_reduction_percent,valid_from,valid_to,updated_at_source,applicable_nfe,source_url,indicators,format_warning,source_sheet,source_row,now(),now() FROM cclass_catalog_entries WHERE catalog_version_id=?',[$new->id,$version->id]);DB::statement('INSERT INTO ncm_class_trib_entries (id,catalog_version_id,ncm_raw,ncm,ncm_level,ex_code,description,reference_rate,expected_cst,expected_cclass_trib,reduction_type,legal_reference_raw,conditions,valid_from,valid_to,allow_child_inheritance,inherited_ncm,status,validation_issues,source_sheet,source_row,created_by,updated_by,created_at,updated_at) SELECT gen_random_uuid(),?,ncm_raw,ncm,ncm_level,ex_code,description,reference_rate,expected_cst,expected_cclass_trib,reduction_type,legal_reference_raw,conditions,valid_from,valid_to,allow_child_inheritance,inherited_ncm,status,validation_issues,source_sheet,source_row,?,?,now(),now() FROM ncm_class_trib_entries WHERE catalog_version_id=?',[$new->id,$r->user()->id,$r->user()->id,$version->id]);return response()->json($new->loadCount('ncmEntries'),201);});}
 public function storeEntry(Request $r,FiscalCatalogVersion $version){$this->draft($version);$d=$this->validateEntry($r);$d['catalog_version_id']=$version->id;$d['created_by']=$d['updated_by']=$r->user()->id;$d['source_sheet']='MANUAL';$d['source_row']=((int)$version->ncmEntries()->max('source_row'))+1;$d['status']='valid';return response()->json(NcmClassTribEntry::create($d),201);}
 public function updateEntry(Request $r,FiscalCatalogVersion $version,NcmClassTribEntry $entry){$this->draft($version);abort_unless($entry->catalog_version_id===$version->id,404);$d=$this->validateEntry($r,true);$d['updated_by']=$r->user()->id;$d['status']='valid';$d['validation_issues']=[];$entry->update($d);return $entry->fresh();}
 public function deleteEntry(FiscalCatalogVersion $version,NcmClassTribEntry $entry){$this->draft($version);abort_unless($entry->catalog_version_id===$version->id,404);$entry->delete();return response()->noContent();}
 public function import(Request $r){$d=$r->validate(['file'=>'required|file|mimes:xlsx|max:102400','version'=>'required|string|max:80|unique:fiscal_catalog_versions,version','name'=>'required|string|max:255','valid_from'=>'required|date','base_version_id'=>'nullable|uuid|exists:fiscal_catalog_versions,id']);$file=$r->file('file');$hash=hash_file('sha256',$file->getRealPath());$path='catalog-imports/'.Str::uuid().'.xlsx';Storage::disk(config('filesystems.default'))->put($path,file_get_contents($file->getRealPath()));$v=FiscalCatalogVersion::create(['name'=>$d['name'],'version'=>$d['version'],'status'=>'importing','valid_from'=>$d['valid_from'],'source_filename'=>$file->getClientOriginalName(),'source_sha256'=>$hash,'storage_path'=>$path,'manifest'=>['base_version_id'=>$d['base_version_id']??null],'created_by'=>$r->user()->id]);ImportCatalogSpreadsheet::dispatch($v->id)->onQueue('high');return response()->json($v,202);}
 public function publish(Request $r,FiscalCatalogVersion $version){$this->draft($version,['draft','validated']);$errors=$version->issues()->where('severity','error')->count()+$version->ncmEntries()->where('status','error')->count();abort_if($errors>0,422,"A versão possui {$errors} erros impeditivos.");DB::transaction(function()use($version,$r){FiscalCatalogVersion::where('status','published')->whereKeyNot($version->id)->update(['status'=>'superseded']);$version->update(['status'=>'published','approved_by'=>$r->user()->id,'approved_at'=>now(),'published_at'=>now()]);});return $version->fresh();}
 public function compare(FiscalCatalogVersion $version,FiscalCatalogVersion $other){$sql='SELECT COALESCE(a.ncm,b.ncm) ncm,COALESCE(a.ex_code,b.ex_code) ex_code,a.expected_cst old_cst,b.expected_cst new_cst,a.expected_cclass_trib old_cclass,b.expected_cclass_trib new_cclass,CASE WHEN a.id IS NULL THEN \'added\' WHEN b.id IS NULL THEN \'removed\' ELSE \'changed\' END change_type FROM ncm_class_trib_entries a FULL OUTER JOIN ncm_class_trib_entries b ON a.ncm=b.ncm AND COALESCE(a.ex_code,\'\')=COALESCE(b.ex_code,\'\') AND a.catalog_version_id=? AND b.catalog_version_id=? WHERE (a.catalog_version_id=? OR b.catalog_version_id=?) AND (a.id IS NULL OR b.id IS NULL OR a.expected_cst IS DISTINCT FROM b.expected_cst OR a.expected_cclass_trib IS DISTINCT FROM b.expected_cclass_trib) LIMIT 5000';return DB::select($sql,[$version->id,$other->id,$version->id,$other->id]);}
 private function draft(FiscalCatalogVersion $v,array $allowed=['draft','validated']):void{abort_unless(in_array($v->status,$allowed,true),409,'Versões publicadas são imutáveis; crie uma revisão.');}
 private function validateEntry(Request $r,bool $partial=false):array{$sometimes=$partial?'sometimes|':'';return $r->validate(['ncm'=>$sometimes.'required|regex:/^\d{8}$/','ex_code'=>'nullable|string|max:8','description'=>$sometimes.'required|string','expected_cst'=>$sometimes.'nullable|regex:/^\d{3}$/','expected_cclass_trib'=>$sometimes.'nullable|regex:/^\d{6,12}$/','reference_rate'=>'nullable|numeric','reduction_type'=>'nullable|string','legal_reference_raw'=>'nullable|string','conditions'=>'nullable|array','valid_from'=>'nullable|date','valid_to'=>'nullable|date|after_or_equal:valid_from','allow_child_inheritance'=>'boolean']);}
}
