<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema; use Illuminate\Support\Facades\DB;
return new class extends Migration {
 public function up(): void {
  DB::statement('CREATE EXTENSION IF NOT EXISTS pgcrypto');
  Schema::create('companies',function(Blueprint $t){$t->uuid('id')->primary();$t->string('legal_name');$t->string('trade_name')->nullable();$t->string('tax_id',14)->unique();$t->string('state_registration')->nullable();$t->string('timezone')->default('America/Sao_Paulo');$t->boolean('active')->default(true);$t->jsonb('settings')->default('{}');$t->timestampsTz();});
  Schema::create('company_user',function(Blueprint $t){$t->foreignUuid('company_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->boolean('is_default')->default(false);$t->timestamps();$t->primary(['company_id','user_id']);});
  Schema::create('fiscal_catalog_versions',function(Blueprint $t){$t->uuid('id')->primary();$t->string('name');$t->string('version')->unique();$t->string('status')->default('draft')->index();$t->date('valid_from')->nullable()->index();$t->date('valid_to')->nullable();$t->string('source_filename')->nullable();$t->string('source_sha256',64)->nullable();$t->string('storage_path')->nullable();$t->jsonb('manifest')->default('{}');$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('approved_by')->nullable()->constrained('users')->nullOnDelete();$t->timestampTz('approved_at')->nullable();$t->timestampTz('published_at')->nullable();$t->timestampsTz();});
  Schema::create('cst_catalog_entries',function(Blueprint $t){$t->id();$t->foreignUuid('catalog_version_id')->constrained('fiscal_catalog_versions')->cascadeOnDelete();$t->string('cst',4);$t->text('description')->nullable();$t->boolean('applicable_nfe')->default(false);$t->jsonb('indicators')->default('{}');$t->string('source_sheet')->nullable();$t->unsignedInteger('source_row')->nullable();$t->timestampsTz();$t->unique(['catalog_version_id','cst']);});
  Schema::create('cclass_catalog_entries',function(Blueprint $t){$t->id();$t->foreignUuid('catalog_version_id')->constrained('fiscal_catalog_versions')->cascadeOnDelete();$t->string('cclass_trib',12);$t->string('cst',4)->index();$t->text('name')->nullable();$t->text('description')->nullable();$t->text('legal_basis')->nullable();$t->text('law_text')->nullable();$t->string('rate_type')->nullable();$t->decimal('ibs_reduction_percent',10,4)->nullable();$t->decimal('cbs_reduction_percent',10,4)->nullable();$t->date('valid_from')->nullable();$t->date('valid_to')->nullable();$t->date('updated_at_source')->nullable();$t->boolean('applicable_nfe')->default(false);$t->text('source_url')->nullable();$t->jsonb('indicators')->default('{}');$t->boolean('format_warning')->default(false);$t->string('source_sheet')->nullable();$t->unsignedInteger('source_row')->nullable();$t->timestampsTz();$t->unique(['catalog_version_id','cclass_trib']);$t->index(['catalog_version_id','cst']);});
  Schema::create('ncm_class_trib_entries',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('catalog_version_id')->constrained('fiscal_catalog_versions')->cascadeOnDelete();$t->string('ncm_raw')->nullable();$t->string('ncm',12)->nullable()->index();$t->string('ncm_level',20)->default('item');$t->string('ex_code',8)->nullable();$t->text('description')->nullable();$t->decimal('reference_rate',12,6)->nullable();$t->string('expected_cst',4)->nullable()->index();$t->string('expected_cclass_trib',12)->nullable()->index();$t->string('reduction_type')->nullable();$t->string('legal_reference_raw')->nullable();$t->jsonb('conditions')->default('{}');$t->date('valid_from')->nullable();$t->date('valid_to')->nullable();$t->boolean('allow_child_inheritance')->default(false);$t->boolean('inherited_ncm')->default(false);$t->string('status',20)->default('valid')->index();$t->jsonb('validation_issues')->default('[]');$t->string('source_sheet')->nullable();$t->unsignedInteger('source_row')->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete();$t->timestampsTz();$t->unique(['catalog_version_id','source_sheet','source_row']);$t->index(['catalog_version_id','ncm','ex_code','valid_from','valid_to'],'ncm_lookup_idx');});
  Schema::create('catalog_import_issues',function(Blueprint $t){$t->id();$t->foreignUuid('catalog_version_id')->constrained('fiscal_catalog_versions')->cascadeOnDelete();$t->string('code')->index();$t->string('severity',20)->index();$t->string('source_sheet')->nullable();$t->unsignedInteger('source_row')->nullable();$t->text('message');$t->jsonb('context')->default('{}');$t->timestampsTz();});
  Schema::create('analysis_batches',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('company_id')->constrained()->cascadeOnDelete();$t->foreignUuid('catalog_version_id')->constrained('fiscal_catalog_versions')->restrictOnDelete();$t->string('name');$t->string('status',30)->default('pending')->index();$t->date('period_start')->nullable();$t->date('period_end')->nullable();$t->unsignedInteger('total_files')->default(0);$t->unsignedInteger('processed_files')->default(0);$t->unsignedInteger('document_count')->default(0);$t->unsignedInteger('item_count')->default(0);$t->unsignedInteger('finding_count')->default(0);$t->decimal('progress',7,4)->default(0);$t->jsonb('summary')->default('{}');$t->jsonb('error')->nullable();$t->foreignId('created_by')->constrained('users')->restrictOnDelete();$t->timestampTz('started_at')->nullable();$t->timestampTz('finished_at')->nullable();$t->timestampsTz();});
  Schema::create('source_files',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('analysis_batch_id')->constrained()->cascadeOnDelete();$t->string('original_name');$t->string('mime_type')->nullable();$t->unsignedBigInteger('size');$t->string('sha256',64)->index();$t->string('storage_path');$t->string('status',20)->default('uploaded');$t->jsonb('metadata')->default('{}');$t->timestampsTz();$t->unique(['analysis_batch_id','sha256']);});
  Schema::create('fiscal_documents',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('analysis_batch_id')->constrained()->cascadeOnDelete();$t->foreignUuid('source_file_id')->nullable()->constrained()->nullOnDelete();$t->string('access_key',44)->nullable()->index();$t->string('model',3)->nullable();$t->string('series',10)->nullable();$t->string('number',20)->nullable();$t->timestampTz('issued_at')->nullable()->index();$t->string('direction',10)->nullable()->index();$t->string('status',30)->default('parsed')->index();$t->string('issuer_tax_id',14)->nullable()->index();$t->string('recipient_tax_id',14)->nullable()->index();$t->decimal('total_value',18,2)->default(0);$t->decimal('ibs_cbs_base',18,2)->default(0);$t->decimal('ibs_value',18,2)->default(0);$t->decimal('cbs_value',18,2)->default(0);$t->unsignedInteger('item_count')->default(0);$t->jsonb('normalized')->default('{}');$t->text('xml_storage_path')->nullable();$t->timestampsTz();$t->unique(['analysis_batch_id','access_key']);});
  Schema::create('fiscal_items',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('fiscal_document_id')->constrained()->cascadeOnDelete();$t->unsignedInteger('item_number');$t->string('product_code')->nullable();$t->text('description')->nullable();$t->string('ncm',12)->nullable()->index();$t->string('ex_code',8)->nullable();$t->string('cfop',8)->nullable();$t->string('actual_cst',4)->nullable();$t->string('actual_cclass_trib',12)->nullable();$t->string('expected_cst',4)->nullable();$t->string('expected_cclass_trib',12)->nullable();$t->string('classification_status',40)->nullable()->index();$t->decimal('product_value',18,2)->default(0);$t->decimal('ibs_cbs_base_xml',18,2)->default(0);$t->decimal('ibs_cbs_base_recalculated',18,2)->default(0);$t->decimal('base_difference',18,2)->default(0);$t->decimal('ibs_xml',18,2)->default(0);$t->decimal('ibs_recalculated',18,2)->default(0);$t->decimal('cbs_xml',18,2)->default(0);$t->decimal('cbs_recalculated',18,2)->default(0);$t->jsonb('tax_components')->default('{}');$t->jsonb('catalog_match')->default('{}');$t->timestampsTz();$t->unique(['fiscal_document_id','item_number']);});
  Schema::create('findings',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('analysis_batch_id')->constrained()->cascadeOnDelete();$t->foreignUuid('fiscal_document_id')->nullable()->constrained()->cascadeOnDelete();$t->foreignUuid('fiscal_item_id')->nullable()->constrained()->cascadeOnDelete();$t->string('rule_code')->index();$t->string('rule_version')->nullable();$t->string('severity',20)->index();$t->string('category')->index();$t->string('title');$t->text('description');$t->text('impact')->nullable();$t->text('recommended_action')->nullable();$t->string('status',20)->default('open')->index();$t->decimal('confidence',7,4)->nullable();$t->jsonb('evidence')->default('{}');$t->foreignId('assigned_to')->nullable()->constrained('users')->nullOnDelete();$t->text('resolution_notes')->nullable();$t->timestampTz('resolved_at')->nullable();$t->timestampsTz();});
  Schema::create('report_artifacts',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('analysis_batch_id')->constrained()->cascadeOnDelete();$t->string('type',20);$t->string('template_version');$t->string('storage_path');$t->string('sha256',64)->nullable();$t->unsignedBigInteger('size')->nullable();$t->jsonb('metadata')->default('{}');$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestampsTz();});
  Schema::create('audit_logs',function(Blueprint $t){$t->bigIncrements('id');$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->uuid('company_id')->nullable()->index();$t->string('action')->index();$t->string('entity_type')->nullable();$t->string('entity_id')->nullable();$t->string('ip_address',45)->nullable();$t->text('user_agent')->nullable();$t->string('request_id')->nullable()->index();$t->jsonb('before')->nullable();$t->jsonb('after')->nullable();$t->jsonb('metadata')->default('{}');$t->timestampTz('created_at')->useCurrent()->index();});
 }
 public function down():void{foreach(['audit_logs','report_artifacts','findings','fiscal_items','fiscal_documents','source_files','analysis_batches','catalog_import_issues','ncm_class_trib_entries','cclass_catalog_entries','cst_catalog_entries','fiscal_catalog_versions','company_user','companies'] as $n)Schema::dropIfExists($n);}
};
