<script setup lang="ts">
import {computed,onBeforeUnmount,onMounted,ref} from 'vue';
import {useRoute,useRouter} from 'vue-router';
import {AgGridVue} from 'ag-grid-vue3';
import {api,dateTime,money,messageOf} from '@/lib/api';
import StatusBadge from '@/components/StatusBadge.vue';

const route=useRoute(),router=useRouter(),id=String(route.params.id);
const batch=ref<any>(),tab=ref('documents'),documents=ref<any[]>([]),findings=ref<any[]>([]),logs=ref<any[]>([]),analytics=ref<any>();
const loading=ref(true),reprocessing=ref(false),pageError=ref('');let pollTimer:number|undefined;
const docCols=[{field:'number',headerName:'NF',width:90},{field:'issued_at',headerName:'Emissão',valueFormatter:(p:any)=>dateTime(p.value),width:145},{field:'direction',headerName:'Direção',width:95},{field:'issuer_tax_id',headerName:'Emitente',width:140},{field:'recipient_tax_id',headerName:'Destinatário',width:140},{field:'total_value',headerName:'Valor NF',valueFormatter:(p:any)=>money(p.value),width:140},{field:'ibs_cbs_base',headerName:'Base IBS/CBS',valueFormatter:(p:any)=>money(p.value),width:145},{field:'items_count',headerName:'Itens',width:75},{field:'status',headerName:'Status',width:110}];
const findingCols=[{field:'severity',headerName:'Severidade',width:110},{field:'category',headerName:'Categoria',width:145},{field:'rule_code',headerName:'Regra',width:180},{field:'title',headerName:'Achado',flex:1,minWidth:240},{field:'fiscal_document.number',headerName:'NF',width:85},{field:'status',headerName:'Status',width:105}];
onMounted(load);onBeforeUnmount(()=>window.clearTimeout(pollTimer));
async function load(){window.clearTimeout(pollTimer);try{const [batchResponse]=await Promise.all([api.get(`/analyses/${id}`),loadDocuments(),loadFindings(),loadLogs(),loadAnalytics()]);batch.value=batchResponse.data;pageError.value='';if(['uploading','queued','processing','retrying'].includes(batch.value.status))pollTimer=window.setTimeout(load,5000)}catch(error){pageError.value=messageOf(error)}finally{loading.value=false}}
async function loadDocuments(){documents.value=(await api.get(`/analyses/${id}/documents`,{params:{per_page:500}})).data.data}async function loadFindings(){findings.value=(await api.get(`/analyses/${id}/findings`,{params:{per_page:500}})).data.data}async function loadLogs(){logs.value=(await api.get(`/analyses/${id}/logs`,{params:{per_page:200}})).data.data}async function loadAnalytics(){analytics.value=(await api.get(`/analyses/${id}/analytics`)).data}
function openDoc(event:any){router.push(`/analises/${id}/documentos/${event.data.id}`)}
async function downloadUrl(url:string,filename:string){const response=await api.get(url,{responseType:'blob'});const objectUrl=URL.createObjectURL(response.data),anchor=document.createElement('a');anchor.href=objectUrl;anchor.download=filename;anchor.click();URL.revokeObjectURL(objectUrl)}
async function downloadReport(report:any){await downloadUrl(`/reports/${report.id}/download`,`auditoria-${id}.${report.type==='pdf'?'pdf':'xlsx'}`)}
async function resolve(finding:any){const notes=prompt('Informe a justificativa da resolução:');if(notes===null)return;await api.patch(`/analyses/${id}/findings/${finding.id}`,{status:'resolved',resolution_notes:notes});await loadFindings()}
async function reprocess(){if(!confirm('Criar uma nova auditoria usando os mesmos arquivos de origem? O lote atual será preservado.'))return;reprocessing.value=true;pageError.value='';try{const {data}=await api.post(`/analyses/${id}/reprocess`);await router.push(`/analises/${data.id}`)}catch(error){pageError.value=messageOf(error)}finally{reprocessing.value=false}}
const totals=computed(()=>batch.value?.summary||{}),failure=computed(()=>batch.value?.error||{}),active=computed(()=>['uploading','queued','processing','retrying'].includes(batch.value?.status));const logContext=(entry:any)=>Object.keys(entry.context||{}).length?JSON.stringify(entry.context,null,2):'';
</script>
<template>
  <div v-if="loading" class="card">Carregando auditoria...</div><template v-else-if="batch"><p v-if="pageError" class="error">{{pageError}}</p>
    <section class="card hero"><div><div class="eyebrow">{{batch.company.legal_name}} · {{batch.catalog_version.version}}</div><h2>{{batch.name}}</h2><p>{{batch.period_start||'Período não informado'}} a {{batch.period_end||'—'}} · {{dateTime(batch.created_at)}}</p></div><div class="actions"><StatusBadge :value="batch.status"/><button v-if="batch.can_reprocess" :disabled="reprocessing" @click="reprocess">{{reprocessing?'Enviando...':'Reprocessar'}}</button><button v-for="r in batch.reports" :key="r.id" @click="downloadReport(r)">Baixar {{r.type.toUpperCase()}}</button></div></section>
    <section v-if="batch.status==='failed'" class="card failure-card"><div class="failure-heading"><div><span class="badge badge-error">Falha</span><h3>Não foi possível concluir esta auditoria</h3></div><button v-if="batch.can_reprocess" :disabled="reprocessing" @click="reprocess">Reprocessar agora</button></div><p>{{failure.message||'O processamento terminou com erro.'}}</p><dl><dt>Código</dt><dd><code>{{failure.code||'ANALYSIS_FAILED'}}</code></dd><dt>Incidente</dt><dd><code>{{failure.incident_id||'—'}}</code></dd><dt>Tentativa</dt><dd>{{failure.attempt||batch.attempt_count||'—'}}</dd><dt>Ocorrido em</dt><dd>{{dateTime(failure.occurred_at||batch.finished_at)}}</dd><template v-if="failure.technical_message"><dt>Detalhe técnico</dt><dd><code>{{failure.technical_message}}</code></dd></template><template v-if="failure.response_body"><dt>Resposta do serviço</dt><dd><code>{{failure.response_body}}</code></dd></template></dl></section>
    <section class="kpis"><article><span>Documentos</span><strong>{{batch.document_count}}</strong></article><article><span>Valor total</span><strong>{{money(totals.total_value)}}</strong></article><article><span>Base IBS/CBS</span><strong>{{money(totals.ibs_cbs_base)}}</strong></article><article><span>Tentativas</span><strong>{{batch.attempt_count||0}}</strong></article></section>
    <p v-if="active" class="hint">Processamento em andamento. Atualização automática a cada 5 segundos.</p><p v-else-if="!batch.can_reprocess&&batch.reprocess_block_reason" class="hint">{{batch.reprocess_block_reason}}</p>
    <div class="tabs"><button :class="{active:tab==='documents'}" @click="tab='documents'">Documentos</button><button :class="{active:tab==='analytics'}" @click="tab='analytics'">Análise crítica</button><button :class="{active:tab==='findings'}" @click="tab='findings'">Críticas ({{findings.length}})</button><button :class="{active:tab==='logs'}" @click="tab='logs'">Processamento e erros ({{batch.application_logs_count}})</button><button :class="{active:tab==='method'}" @click="tab='method'">Método</button></div>
    <section class="card" v-show="tab==='documents'"><AgGridVue theme="legacy" class="ag-theme-quartz grid" :rowData="documents" :columnDefs="docCols" :pagination="true" :paginationPageSize="50" @rowClicked="openDoc"/><p class="hint">Selecione uma nota para abrir XML, DANFE, itens e tributos em tela completa.</p></section>
    <section class="card" v-show="tab==='analytics'" v-if="analytics"><div class="analytics-grid"><div class="detail-block"><h3>Severidade</h3><dl class="detail-list"><template v-for="(value,key) in analytics.severity_counts" :key="key"><dt>{{key}}</dt><dd>{{value}}</dd></template></dl></div><div class="detail-block"><h3>Camadas de análise</h3><dl class="detail-list"><template v-for="(value,key) in analytics.category_counts" :key="key"><dt>{{key}}</dt><dd>{{value}}</dd></template></dl></div></div><h3>Conciliação por chassi</h3><div class="table-scroll"><table><thead><tr><th>Chassi</th><th>NF entrada</th><th>NF saída</th><th>Custo</th><th>Venda</th><th>Margem</th><th>Situação</th></tr></thead><tbody><tr v-for="row in analytics.reconciliation" :key="row.chassis"><td><code>{{row.chassis}}</code></td><td>{{row.input_document||'—'}}</td><td>{{row.output_document||'—'}}</td><td>{{money(row.cost)}}</td><td>{{money(row.sale)}}</td><td>{{money(row.margin)}}</td><td><StatusBadge :value="row.status"/></td></tr></tbody></table></div><h3>Limitações e salvaguardas</h3><ul class="check-list"><li v-for="note in analytics.limitations" :key="note">{{note}}</li></ul></section>
    <section class="card" v-show="tab==='findings'"><AgGridVue theme="legacy" class="ag-theme-quartz grid" :rowData="findings" :columnDefs="findingCols" :pagination="true" :paginationPageSize="50" @rowDoubleClicked="resolve($event.data)"/><p class="hint">Clique duas vezes em uma crítica para registrar a resolução.</p></section>
    <section class="card" v-show="tab==='logs'"><div class="card-title"><div><h2>Histórico do processamento</h2><p>Eventos persistidos em ordem reversa.</p></div><button @click="downloadUrl(`/analyses/${id}/logs/export`,`auditoria-${id}-logs.ndjson`)">Baixar todos</button></div><div v-if="logs.length" class="log-timeline"><article v-for="entry in logs" :key="entry.id" class="log-entry"><span :class="`log-marker badge-${entry.level}`"></span><div><div class="log-heading"><strong>{{entry.event}}</strong><StatusBadge :value="entry.level"/><button @click="downloadUrl(`/analyses/${id}/logs/${entry.id}/download`,`audit-log-${entry.id}.json`)">Baixar</button><time>{{dateTime(entry.created_at)}}</time></div><p>{{entry.message}}</p><p class="hint">{{entry.component}}<template v-if="entry.attempt"> · tentativa {{entry.attempt}}</template><template v-if="entry.incident_id"> · incidente <code>{{entry.incident_id}}</code></template></p><details v-if="logContext(entry)"><summary>Contexto técnico</summary><pre>{{logContext(entry)}}</pre></details></div></article></div><p v-else class="empty-state">Nenhum evento registrado.</p></section>
    <section class="card prose" v-show="tab==='method'"><h3>Rastreabilidade</h3><dl><dt>Versão de catálogo</dt><dd>{{batch.catalog_version.version}}</dd><dt>Hash da fonte</dt><dd><code>{{batch.catalog_version.source_sha256}}</code></dd><dt>Regra de cálculo</dt><dd>UB16-10 item a item, Decimal e ROUND_HALF_UP.</dd><dt>Fonte primária</dt><dd>XML fiscal; o DANFE é somente representação visual.</dd><dt>Snapshot</dt><dd>O resultado permanece vinculado à versão usada.</dd></dl></section>
  </template><p v-else class="error">{{pageError||'Auditoria não encontrada.'}}</p>
</template>
