<script setup lang="ts">
import {onMounted,ref} from 'vue';import {api,messageOf} from '@/lib/api';
const rows=ref<any[]>([]),tenants=ref<any[]>([]),editing=ref<string>(),error=ref('');
const empty=()=>({tenant_id:'',legal_name:'',trade_name:'',tax_id:'',state_registration:'',active:true});const form=ref<any>(empty());
async function load(){const [c,t]=await Promise.all([api.get('/companies',{params:{per_page:100}}),api.get('/tenants',{params:{per_page:100}})]);rows.value=c.data.data;tenants.value=t.data.data}
onMounted(load);function edit(row:any){editing.value=row.id;form.value={tenant_id:row.tenant_id,legal_name:row.legal_name,trade_name:row.trade_name||'',tax_id:row.tax_id,state_registration:row.state_registration||'',active:row.active};error.value=''}function cancel(){editing.value=undefined;form.value=empty();error.value=''}
async function save(){try{if(editing.value)await api.patch(`/companies/${editing.value}`,form.value);else await api.post('/companies',form.value);cancel();await load()}catch(e){error.value=messageOf(e)}}
</script>
<template><div class="split"><section class="card"><div class="card-title"><div><h2>Empresas</h2><p>Estabelecimentos vinculados aos tenants.</p></div></div><div class="table-scroll"><table><thead><tr><th>Razão social</th><th>Tenant</th><th>CNPJ</th><th>IE</th><th>Status</th><th></th></tr></thead><tbody><tr v-for="c in rows" :key="c.id"><td>{{c.legal_name}}<small v-if="c.trade_name"><br>{{c.trade_name}}</small></td><td>{{c.tenant?.trade_name||c.tenant?.legal_name}}</td><td><code>{{c.tax_id}}</code></td><td>{{c.state_registration||'—'}}</td><td>{{c.active?'Ativa':'Inativa'}}</td><td><button @click="edit(c)">Editar</button></td></tr></tbody></table></div></section><form class="card form-grid one" @submit.prevent="save"><h2>{{editing?'Editar empresa':'Nova empresa'}}</h2><label>Tenant<select v-model="form.tenant_id" required><option value="" disabled>Selecione</option><option v-for="t in tenants" :key="t.id" :value="t.id">{{t.trade_name||t.legal_name}} · {{t.tax_id}}</option></select></label><label>Razão social<input v-model="form.legal_name" required></label><label>Nome fantasia<input v-model="form.trade_name"></label><label>CNPJ<input v-model="form.tax_id" required :disabled="!!editing"></label><label>Inscrição estadual<input v-model="form.state_registration"></label><label v-if="editing"><span><input v-model="form.active" type="checkbox" style="width:auto"> Empresa ativa</span></label><p v-if="error" class="error">{{error}}</p><div class="form-actions"><button v-if="editing" type="button" @click="cancel">Cancelar</button><button class="primary">{{editing?'Salvar alterações':'Cadastrar empresa'}}</button></div></form></div></template>
