<script setup lang="ts">
import {computed,onBeforeUnmount,onMounted,ref,watch} from 'vue';
import {useRoute} from 'vue-router';
import {api,dateTime,formatXml,money,messageOf} from '@/lib/api';
import StatusBadge from '@/components/StatusBadge.vue';
const route=useRoute(),batchId=String(route.params.id),documentId=String(route.params.documentId);
const document=ref<any>(),tab=ref('summary'),rawXml=ref(''),auxiliaryDocumentUrl=ref(''),error=ref(''),loading=ref(true),auxiliaryDocumentLoading=ref(false);
const normalized=computed(()=>document.value?.normalized||{});
const auxiliaryLabels:Record<string,string>={55:'DANFE',65:'DANFCE',57:'DACTE',67:'DACTE OS',58:'DAMDFE'};
const auxiliaryType=computed(()=>document.value?.auxiliary_document_type||auxiliaryLabels[String(document.value?.model||'')]||'documento auxiliar');
const auxiliaryAvailable=computed(()=>Boolean(document.value?.auxiliary_document_storage_path||document.value?.danfe_storage_path));
const prettyXml=computed(()=>formatXml(rawXml.value));
onMounted(load);onBeforeUnmount(()=>{if(auxiliaryDocumentUrl.value)URL.revokeObjectURL(auxiliaryDocumentUrl.value)});watch(tab,value=>{if(value==='auxiliary-document')loadAuxiliaryDocument()});
async function load(){try{const [{data},xmlResponse]=await Promise.all([api.get(`/analyses/${batchId}/documents/${documentId}`),api.get(`/analyses/${batchId}/documents/${documentId}/xml`,{responseType:'text'})]);document.value=data;rawXml.value=xmlResponse.data}catch(reason){error.value=messageOf(reason)}finally{loading.value=false}}
async function loadAuxiliaryDocument(){if(auxiliaryDocumentUrl.value||!auxiliaryAvailable.value)return;auxiliaryDocumentLoading.value=true;try{const response=await api.get(`/analyses/${batchId}/documents/${documentId}/auxiliary-document`,{responseType:'blob'});auxiliaryDocumentUrl.value=URL.createObjectURL(response.data)}catch(reason){error.value=messageOf(reason)}finally{auxiliaryDocumentLoading.value=false}}
async function requestAuxiliaryDocument(){auxiliaryDocumentLoading.value=true;error.value='';try{const {data}=await api.post(`/analyses/${batchId}/documents/${documentId}/auxiliary-document/generate`);document.value=data.data;window.setTimeout(load,1500)}catch(reason){error.value=messageOf(reason)}finally{auxiliaryDocumentLoading.value=false}}
async function download(kind:'xml'|'auxiliary-document'){const response=await api.get(`/analyses/${batchId}/documents/${documentId}/${kind}`,{params:{download:1},responseType:'blob'});const url=URL.createObjectURL(response.data),a=window.document.createElement('a');a.href=url;a.download=`${kind==='xml'?'documento-fiscal':auxiliaryType.value}-${document.value.access_key}.${kind==='xml'?'xml':'pdf'}`;a.click();URL.revokeObjectURL(url)}
function entries(value:any){return Object.entries(value||{})}function display(value:any){return typeof value==='object'?JSON.stringify(value,null,2):(value??'—')}
const fieldLabels:Record<string,string>={nature:'Natureza da operação',operation_type:'Tipo da operação',destination:'Destino da operação',purpose:'Finalidade',consumer:'Consumidor final',presence:'Indicador de presença',environment:'Ambiente',references:'NF-e referenciadas',name:'Nome / razão social',trade_name:'Nome fantasia',tax_id:'CNPJ / CPF',state_registration:'Inscrição estadual',municipal_registration:'Inscrição municipal',tax_regime:'Regime tributário',address:'Endereço',phone:'Telefone',email:'E-mail',number:'Número',status_code:'Código do status',status_reason:'Situação',received_at:'Recebido em',freight_mode:'Modalidade do frete',carrier:'Transportador',vehicle_plate:'Placa',vehicle_state:'UF do veículo'};
function labelOf(key:string){return fieldLabels[key]||key.replaceAll('_',' ')}
</script>
<template><div v-if="loading" class="card">Carregando documento fiscal...</div><p v-else-if="error&&!document" class="error">{{error}}</p><template v-else-if="document">
  <section class="card hero"><div><div class="eyebrow"><RouterLink :to="`/analises/${batchId}`">← Voltar à auditoria</RouterLink></div><h2>Documento {{document.number}} · Série {{document.series}}</h2><p><code>{{document.access_key}}</code></p></div><div class="document-actions"><StatusBadge :value="document.status"/><button @click="download('xml')">Baixar XML</button><button v-if="auxiliaryAvailable" @click="download('auxiliary-document')">Baixar {{auxiliaryType}}</button></div></section><p v-if="error" class="error">{{error}}</p>
  <section class="kpis"><article><span>Valor da NF</span><strong>{{money(document.total_value)}}</strong></article><article><span>Base IBS/CBS</span><strong>{{money(document.ibs_cbs_base)}}</strong></article><article><span>IBS</span><strong>{{money(document.ibs_value)}}</strong></article><article><span>CBS</span><strong>{{money(document.cbs_value)}}</strong></article></section>
  <div class="tabs"><button :class="{active:tab==='summary'}" @click="tab='summary'">Resumo</button><button :class="{active:tab==='items'}" @click="tab='items'">Itens ({{document.items.length}})</button><button :class="{active:tab==='taxes'}" @click="tab='taxes'">Tributos</button><button :class="{active:tab==='xml'}" @click="tab='xml'">XML</button><button :class="{active:tab==='auxiliary-document'}" @click="tab='auxiliary-document'">{{auxiliaryType}}</button><button :class="{active:tab==='findings'}" @click="tab='findings'">Críticas ({{document.findings.length}})</button></div>
  <section v-show="tab==='summary'" class="card"><div class="detail-grid"><article class="detail-block"><h3>Identificação</h3><dl class="detail-list"><dt>Emissão</dt><dd>{{dateTime(document.issued_at)}}</dd><dt>Direção</dt><dd>{{document.direction}}</dd><template v-for="([key,value]) in entries(normalized.identification)" :key="key"><dt>{{labelOf(key)}}</dt><dd>{{display(value)}}</dd></template></dl></article><article class="detail-block"><h3>Emitente</h3><dl class="detail-list"><template v-for="([key,value]) in entries(normalized.issuer)" :key="key"><dt>{{labelOf(key)}}</dt><dd><pre v-if="typeof value==='object'">{{display(value)}}</pre><template v-else>{{display(value)}}</template></dd></template></dl></article><article class="detail-block"><h3>Destinatário</h3><dl class="detail-list"><template v-for="([key,value]) in entries(normalized.recipient)" :key="key"><dt>{{labelOf(key)}}</dt><dd><pre v-if="typeof value==='object'">{{display(value)}}</pre><template v-else>{{display(value)}}</template></dd></template></dl></article><article class="detail-block"><h3>Protocolo</h3><dl class="detail-list"><template v-for="([key,value]) in entries(normalized.protocol)" :key="key"><dt>{{labelOf(key)}}</dt><dd>{{display(value)}}</dd></template></dl></article><article class="detail-block"><h3>Totais da NF-e</h3><dl class="detail-list"><template v-for="([key,value]) in entries(normalized.totals)" :key="key"><dt>{{key}}</dt><dd>{{money(value)}}</dd></template></dl></article><article class="detail-block"><h3>Transporte</h3><dl class="detail-list"><template v-for="([key,value]) in entries(normalized.transport)" :key="key"><dt>{{labelOf(key)}}</dt><dd><pre v-if="typeof value==='object'">{{display(value)}}</pre><template v-else>{{display(value)}}</template></dd></template></dl></article><article class="detail-block"><h3>Cobrança e pagamento</h3><pre>{{display({cobranca:normalized.billing,pagamentos:normalized.payments})}}</pre></article><article class="detail-block"><h3>Informações adicionais</h3><pre>{{display(normalized.additional_information)}}</pre></article></div></section>
  <section v-show="tab==='items'" class="card"><div class="table-scroll"><table><thead><tr><th>#</th><th>Produto</th><th>NCM/EX</th><th>CFOP</th><th>Quantidade</th><th>Valor</th><th>Encontrado</th><th>Esperado</th><th>Situação</th></tr></thead><tbody><template v-for="item in document.items" :key="item.id"><tr><td>{{item.item_number}}</td><td><strong>{{item.description}}</strong><small><br>Código {{item.product_code||'—'}}<template v-if="item.details?.ean_taxable||item.details?.ean"> · GTIN {{item.details?.ean_taxable||item.details?.ean}}</template><template v-if="item.chassis"> · Chassi {{item.chassis}}</template><template v-if="item.details?.reconciliation_identity"> · Identidade: {{item.details.reconciliation_identity.label}} ({{item.details.reconciliation_identity.confidence}})</template></small></td><td>{{item.ncm}} / {{item.ex_code||'—'}}</td><td>{{item.cfop}}</td><td>{{item.details?.quantity||'—'}} {{item.details?.unit||''}}</td><td>{{money(item.product_value)}}</td><td>{{item.actual_cst||'—'}} / {{item.actual_cclass_trib||'—'}}</td><td>{{item.expected_cst||'—'}} / {{item.expected_cclass_trib||'—'}}</td><td><StatusBadge :value="item.classification_status"/></td></tr><tr><td></td><td colspan="8"><details><summary>Identificadores, lotes, atributos e tributos do item</summary><pre class="code-view">{{JSON.stringify(item.details,null,2)}}</pre></details></td></tr></template></tbody></table></div></section>
  <section v-show="tab==='taxes'" class="card"><div class="table-scroll"><table><thead><tr><th>Item</th><th>Base XML</th><th>Base recalculada</th><th>Diferença</th><th>IBS XML / recálculo</th><th>CBS XML / recálculo</th><th>Componentes e grupos</th></tr></thead><tbody><tr v-for="item in document.items" :key="item.id"><td>{{item.item_number}} · {{item.description}}</td><td>{{money(item.ibs_cbs_base_xml)}}</td><td>{{money(item.ibs_cbs_base_recalculated)}}</td><td>{{money(item.base_difference)}}</td><td>{{money(item.ibs_xml)}} / {{money(item.ibs_recalculated)}}</td><td>{{money(item.cbs_xml)}} / {{money(item.cbs_recalculated)}}</td><td><details><summary>Detalhar</summary><pre class="code-view">{{JSON.stringify({components:item.tax_components,taxes:item.details?.taxes},null,2)}}</pre></details></td></tr></tbody></table></div></section>
  <section v-show="tab==='xml'" class="card"><div class="card-title"><div><h2>XML fiscal original</h2><p>Conteúdo formatado apenas para leitura; o arquivo baixado permanece idêntico ao recebido.</p></div><button @click="download('xml')">Baixar original</button></div><pre class="code-view">{{prettyXml}}</pre></section>
  <section v-show="tab==='auxiliary-document'" class="card"><div class="card-title"><div><h2>{{auxiliaryType}}</h2><p v-if="document.auxiliary_document_source==='imported_original'">PDF original recebido junto do XML. Ele é preservado e tem prioridade.</p><p v-else-if="document.auxiliary_document_source==='nfephp_generated'">Documento auxiliar padronizado, gerado pelo NFePHP a partir do XML fiscal autorizado. O XML autorizado permanece como a fonte fiscal válida.</p><p v-else-if="document.auxiliary_document_status==='not_supported'">Este modelo não possui renderizador configurado. Para não inventar um PDF, disponibilizamos somente o XML original.</p><p v-else>O documento auxiliar está sendo preparado a partir do XML fiscal.</p></div><button v-if="auxiliaryAvailable" @click="download('auxiliary-document')">Baixar PDF</button><button v-else-if="document.auxiliary_document_status!=='not_supported'" :disabled="auxiliaryDocumentLoading" @click="requestAuxiliaryDocument">{{auxiliaryDocumentLoading?'Solicitando...':`Gerar ${auxiliaryType}`}}</button></div><p v-if="auxiliaryDocumentLoading">Carregando {{auxiliaryType}}...</p><iframe v-else-if="auxiliaryDocumentUrl" class="pdf-frame" :src="auxiliaryDocumentUrl" :title="`${auxiliaryType} do documento fiscal`"></iframe><p v-else class="empty-state">{{document.auxiliary_document_status==='failed'?'Não foi possível gerar o documento auxiliar. Consulte os logs da auditoria.':'Documento auxiliar indisponível para este documento.'}}</p></section>
  <section v-show="tab==='findings'" class="card"><div class="table-scroll"><table><thead><tr><th>Severidade</th><th>Regra</th><th>Título</th><th>Descrição</th><th>Impacto</th><th>Ação</th></tr></thead><tbody><tr v-for="finding in document.findings" :key="finding.id"><td><StatusBadge :value="finding.severity"/></td><td><code>{{finding.rule_code}}</code></td><td>{{finding.title}}</td><td>{{finding.description}}</td><td>{{finding.impact}}</td><td>{{finding.recommended_action}}</td></tr></tbody></table></div></section>
</template></template>
