<script setup lang="ts">
import {computed,onBeforeUnmount,onMounted,ref,watch} from 'vue';
import {useRoute} from 'vue-router';
import {api,dateTime,formatXml,money,messageOf} from '@/lib/api';
import StatusBadge from '@/components/StatusBadge.vue';
const route=useRoute(),batchId=String(route.params.id),documentId=String(route.params.documentId);
const document=ref<any>(),tab=ref('summary'),rawXml=ref(''),danfeUrl=ref(''),error=ref(''),loading=ref(true),danfeLoading=ref(false);
const normalized=computed(()=>document.value?.normalized||{});
const prettyXml=computed(()=>formatXml(rawXml.value));
onMounted(load);onBeforeUnmount(()=>{if(danfeUrl.value)URL.revokeObjectURL(danfeUrl.value)});watch(tab,value=>{if(value==='danfe')loadDanfe()});
async function load(){try{const [{data},xmlResponse]=await Promise.all([api.get(`/analyses/${batchId}/documents/${documentId}`),api.get(`/analyses/${batchId}/documents/${documentId}/xml`,{responseType:'text'})]);document.value=data;rawXml.value=xmlResponse.data}catch(reason){error.value=messageOf(reason)}finally{loading.value=false}}
async function loadDanfe(){if(danfeUrl.value||!document.value?.danfe_storage_path)return;danfeLoading.value=true;try{const response=await api.get(`/analyses/${batchId}/documents/${documentId}/danfe`,{responseType:'blob'});danfeUrl.value=URL.createObjectURL(response.data)}catch(reason){error.value=messageOf(reason)}finally{danfeLoading.value=false}}
async function download(kind:'xml'|'danfe'){const response=await api.get(`/analyses/${batchId}/documents/${documentId}/${kind}`,{params:{download:1},responseType:'blob'});const url=URL.createObjectURL(response.data),a=window.document.createElement('a');a.href=url;a.download=`NFe-${document.value.access_key}.${kind==='xml'?'xml':'pdf'}`;a.click();URL.revokeObjectURL(url)}
function entries(value:any){return Object.entries(value||{})}function display(value:any){return typeof value==='object'?JSON.stringify(value,null,2):(value??'—')}
</script>
<template><div v-if="loading" class="card">Carregando NF-e...</div><p v-else-if="error&&!document" class="error">{{error}}</p><template v-else-if="document">
  <section class="card hero"><div><div class="eyebrow"><RouterLink :to="`/analises/${batchId}`">← Voltar à auditoria</RouterLink></div><h2>NF {{document.number}} · Série {{document.series}}</h2><p><code>{{document.access_key}}</code></p></div><div class="document-actions"><StatusBadge :value="document.status"/><button @click="download('xml')">Baixar XML</button><button v-if="document.danfe_storage_path" @click="download('danfe')">Baixar DANFE</button></div></section><p v-if="error" class="error">{{error}}</p>
  <section class="kpis"><article><span>Valor da NF</span><strong>{{money(document.total_value)}}</strong></article><article><span>Base IBS/CBS</span><strong>{{money(document.ibs_cbs_base)}}</strong></article><article><span>IBS</span><strong>{{money(document.ibs_value)}}</strong></article><article><span>CBS</span><strong>{{money(document.cbs_value)}}</strong></article></section>
  <div class="tabs"><button :class="{active:tab==='summary'}" @click="tab='summary'">Resumo</button><button :class="{active:tab==='items'}" @click="tab='items'">Itens ({{document.items.length}})</button><button :class="{active:tab==='taxes'}" @click="tab='taxes'">Tributos</button><button :class="{active:tab==='xml'}" @click="tab='xml'">XML</button><button :class="{active:tab==='danfe'}" @click="tab='danfe'">DANFE</button><button :class="{active:tab==='findings'}" @click="tab='findings'">Críticas ({{document.findings.length}})</button></div>
  <section v-show="tab==='summary'" class="card"><div class="detail-grid"><article class="detail-block"><h3>Identificação</h3><dl class="detail-list"><dt>Emissão</dt><dd>{{dateTime(document.issued_at)}}</dd><dt>Direção</dt><dd>{{document.direction}}</dd><template v-for="([key,value]) in entries(normalized.identification)" :key="key"><dt>{{key}}</dt><dd>{{display(value)}}</dd></template></dl></article><article class="detail-block"><h3>Emitente</h3><dl class="detail-list"><template v-for="([key,value]) in entries(normalized.issuer)" :key="key"><dt>{{key}}</dt><dd><pre v-if="typeof value==='object'">{{display(value)}}</pre><template v-else>{{display(value)}}</template></dd></template></dl></article><article class="detail-block"><h3>Destinatário</h3><dl class="detail-list"><template v-for="([key,value]) in entries(normalized.recipient)" :key="key"><dt>{{key}}</dt><dd><pre v-if="typeof value==='object'">{{display(value)}}</pre><template v-else>{{display(value)}}</template></dd></template></dl></article><article class="detail-block"><h3>Protocolo</h3><dl class="detail-list"><template v-for="([key,value]) in entries(normalized.protocol)" :key="key"><dt>{{key}}</dt><dd>{{display(value)}}</dd></template></dl></article><article class="detail-block"><h3>Transporte</h3><dl class="detail-list"><template v-for="([key,value]) in entries(normalized.transport)" :key="key"><dt>{{key}}</dt><dd>{{display(value)}}</dd></template></dl></article><article class="detail-block"><h3>Cobrança e pagamento</h3><pre>{{display({billing:normalized.billing,payments:normalized.payments})}}</pre></article></div></section>
  <section v-show="tab==='items'" class="card"><div class="table-scroll"><table><thead><tr><th>#</th><th>Produto</th><th>NCM/EX</th><th>CFOP</th><th>Quantidade</th><th>Valor</th><th>Encontrado</th><th>Esperado</th><th>Situação</th></tr></thead><tbody><template v-for="item in document.items" :key="item.id"><tr><td>{{item.item_number}}</td><td><strong>{{item.description}}</strong><small><br>Código {{item.product_code||'—'}}<template v-if="item.chassis"> · Chassi {{item.chassis}}</template></small></td><td>{{item.ncm}} / {{item.ex_code||'—'}}</td><td>{{item.cfop}}</td><td>{{item.details?.quantity||'—'}} {{item.details?.unit||''}}</td><td>{{money(item.product_value)}}</td><td>{{item.actual_cst||'—'}} / {{item.actual_cclass_trib||'—'}}</td><td>{{item.expected_cst||'—'}} / {{item.expected_cclass_trib||'—'}}</td><td><StatusBadge :value="item.classification_status"/></td></tr><tr><td></td><td colspan="8"><details><summary>Todos os campos do item</summary><pre class="code-view">{{JSON.stringify(item.details,null,2)}}</pre></details></td></tr></template></tbody></table></div></section>
  <section v-show="tab==='taxes'" class="card"><div class="table-scroll"><table><thead><tr><th>Item</th><th>Base XML</th><th>Base recalculada</th><th>Diferença</th><th>IBS XML / recálculo</th><th>CBS XML / recálculo</th><th>Componentes e grupos</th></tr></thead><tbody><tr v-for="item in document.items" :key="item.id"><td>{{item.item_number}} · {{item.description}}</td><td>{{money(item.ibs_cbs_base_xml)}}</td><td>{{money(item.ibs_cbs_base_recalculated)}}</td><td>{{money(item.base_difference)}}</td><td>{{money(item.ibs_xml)}} / {{money(item.ibs_recalculated)}}</td><td>{{money(item.cbs_xml)}} / {{money(item.cbs_recalculated)}}</td><td><details><summary>Detalhar</summary><pre class="code-view">{{JSON.stringify({components:item.tax_components,taxes:item.details?.taxes},null,2)}}</pre></details></td></tr></tbody></table></div></section>
  <section v-show="tab==='xml'" class="card"><div class="card-title"><div><h2>XML fiscal original</h2><p>Conteúdo formatado apenas para leitura; o arquivo baixado permanece idêntico ao recebido.</p></div><button @click="download('xml')">Baixar original</button></div><pre class="code-view">{{prettyXml}}</pre></section>
  <section v-show="tab==='danfe'" class="card"><div class="card-title"><div><h2>DANFE</h2><p>Representação visual anexada; não participa dos cálculos.</p></div><button v-if="document.danfe_storage_path" @click="download('danfe')">Baixar PDF</button></div><p v-if="danfeLoading">Carregando DANFE...</p><iframe v-else-if="danfeUrl" class="pdf-frame" :src="danfeUrl" title="DANFE da NF-e"></iframe><p v-else class="empty-state">Nenhum DANFE correspondente foi enviado com esta NF-e.</p></section>
  <section v-show="tab==='findings'" class="card"><div class="table-scroll"><table><thead><tr><th>Severidade</th><th>Regra</th><th>Título</th><th>Descrição</th><th>Impacto</th><th>Ação</th></tr></thead><tbody><tr v-for="finding in document.findings" :key="finding.id"><td><StatusBadge :value="finding.severity"/></td><td><code>{{finding.rule_code}}</code></td><td>{{finding.title}}</td><td>{{finding.description}}</td><td>{{finding.impact}}</td><td>{{finding.recommended_action}}</td></tr></tbody></table></div></section>
</template></template>
