<script setup lang="ts">
import {computed,onMounted,ref} from 'vue';import {api,messageOf} from '@/lib/api';
const users=ref<any[]>([]),roles=ref<any[]>([]),companies=ref<any[]>([]),tenants=ref<any[]>([]),editing=ref<number>(),error=ref('');
const empty=()=>({name:'',email:'',password:'',role:'Auditor Fiscal',tenant_ids:[] as string[],company_ids:[] as string[],active:true});const form=ref<any>(empty());
const availableCompanies=computed(()=>companies.value.filter(company=>form.value.tenant_ids.includes(company.tenant_id)));
async function load(){const [u,r,c,t]=await Promise.all([api.get('/users'),api.get('/users/roles'),api.get('/companies',{params:{per_page:100}}),api.get('/tenants',{params:{per_page:100}})]);users.value=u.data.data;roles.value=r.data;companies.value=c.data.data;tenants.value=t.data.data}
onMounted(load);function edit(user:any){editing.value=user.id;form.value={name:user.name,email:user.email,password:'',role:user.roles[0]?.name||'Consulta',tenant_ids:user.tenants.map((x:any)=>x.id),company_ids:user.companies.map((x:any)=>x.id),active:user.active};error.value=''}function cancel(){editing.value=undefined;form.value=empty();error.value=''}function tenantChanged(){form.value.company_ids=form.value.company_ids.filter((id:string)=>availableCompanies.value.some(company=>company.id===id))}
async function save(){try{const payload={...form.value};if(editing.value&&!payload.password)delete payload.password;if(editing.value)await api.patch(`/users/${editing.value}`,payload);else await api.post('/users',payload);cancel();await load()}catch(e){error.value=messageOf(e)}}
</script>
<template><div class="split"><section class="card"><div class="card-title"><div><h2>Usuários e permissões</h2><p>Acesso explícito por tenant e por empresa.</p></div></div><div class="table-scroll"><table><thead><tr><th>Nome</th><th>E-mail</th><th>Perfil</th><th>Tenants</th><th>Empresas</th><th>Status</th><th></th></tr></thead><tbody><tr v-for="u in users" :key="u.id"><td>{{u.name}}</td><td>{{u.email}}</td><td>{{u.roles.map((r:any)=>r.name).join(', ')}}</td><td>{{u.tenants.length}}</td><td>{{u.companies.length}}</td><td>{{u.active?'Ativo':'Inativo'}}</td><td><button @click="edit(u)">Editar</button></td></tr></tbody></table></div></section><form class="card form-grid one" @submit.prevent="save"><h2>{{editing?'Editar usuário':'Novo usuário'}}</h2><label>Nome<input v-model="form.name" required></label><label>E-mail<input v-model="form.email" type="email" required></label><label>{{editing?'Nova senha (opcional)':'Senha inicial'}}<input v-model="form.password" type="password" minlength="12" :required="!editing"></label><label>Perfil<select v-model="form.role"><option v-for="r in roles" :key="r.id">{{r.name}}</option></select></label><fieldset><legend>Tenants associados</legend><div class="selection-list"><label v-for="t in tenants" :key="t.id"><input v-model="form.tenant_ids" type="checkbox" :value="t.id" @change="tenantChanged"><span>{{t.trade_name||t.legal_name}}<small><br>{{t.tax_id}}</small></span></label></div></fieldset><fieldset><legend>Empresas permitidas</legend><div class="selection-list"><label v-for="c in availableCompanies" :key="c.id"><input v-model="form.company_ids" type="checkbox" :value="c.id"><span>{{c.trade_name||c.legal_name}}<small><br>{{c.tax_id}}</small></span></label><span v-if="!availableCompanies.length" class="hint">Selecione pelo menos um tenant.</span></div></fieldset><label v-if="editing"><span><input v-model="form.active" type="checkbox" style="width:auto"> Usuário ativo</span></label><p v-if="error" class="error">{{error}}</p><div class="form-actions"><button v-if="editing" type="button" @click="cancel">Cancelar</button><button class="primary">{{editing?'Salvar alterações':'Cadastrar usuário'}}</button></div></form></div></template>
